"""
Django settings for Rhythmify project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path

from decouple import config
from celery.schedules import crontab
import os
import logging.config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ul8up=_nmd9=ejlskj5_6!qjhid*z18s^eup1sg97-^80^ds1="

# SECURITY WARNING: don't process_top_tracks with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "django_celery_results",

    "User",
    "SpotifyController",
    "Profile",
    "Catalog",

    "LastFM",
    "Deezer",

    "Main",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Rhythmify.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                "processors.context_processor.user_header_data",
            ],
        },
    },
]

WSGI_APPLICATION = "Rhythmify.wsgi.application"


# database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "rhythmify",
        "USER": "obscurum",
        "PASSWORD": "admin",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
DJANGO_LOG_LEVEL = getattr(logging, LOG_LEVEL, logging.INFO)
APP_LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(APP_LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # оставляем логгеры Django
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] [%(module)s:%(lineno)d] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "[%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "level": DJANGO_LOG_LEVEL,
        },
        "app_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(APP_LOG_DIR, "app.log"),
            "when": "midnight",
            "backupCount": 7,
            "encoding": "utf-8",
            "formatter": "verbose",
            "level": DJANGO_LOG_LEVEL,
        },
        "errors_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(APP_LOG_DIR, "errors.log"),
            "when": "midnight",
            "backupCount": 14,
            "encoding": "utf-8",
            "formatter": "verbose",
            "level": "ERROR",
        },
        "tests_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(APP_LOG_DIR, "tests.log"),
            "when": "midnight",
            "backupCount": 7,
            "encoding": "utf-8",
            "formatter": "verbose",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "tests": {
            "handlers": ["console", "tests_file"],
            "level": "DEBUG",
            "propagate": False,
        },

        "tasks": {
            "handlers": ["console", "tests_file"],
            "level": "DEBUG",
            "propagate": False,
        },


        # Ваше приложение целиком
        "SpotifyController": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        # Можно сузить до подмодулей
        "SpotifyController.services": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },


        "Main": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "Main.services": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },


        "LastFM": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "LastFM.services": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },


        "Deezer": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },

        "Catalog": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },


        "Profile": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },



        "Search": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },


        "User": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },

        # Django запросы/ошибки
        "django.request": {
            "handlers": ["errors_file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        # SQL в DEV (включайте, когда надо диагностировать)
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "User.CustomUser"

CLIENT_ID = config("CLIENT_ID")
CLIENT_SECRET = config("CLIENT_SECRET")
REDIRECT_URL = config("REDIRECT_URL")
SCOPE = (
    "user-read-currently-playing "
    "user-read-playback-state "
    "playlist-modify-private "
    "playlist-modify-public "
    "user-top-read "
    "user-library-read "
    "user-read-recently-played "
    "user-read-private "
    "playlist-read-private "
    "playlist-read-collaborative "
)

LAST_FM_KEY=config("LAST_FM_KEY")
LAST_FM_SECRET=config("LAST_FM_SECRET")


MEDIA_ROOT = BASE_DIR / "media"

CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672//"
CELERY_RESULT_BACKEND = "django-db"

CELERY_TIMEZONE = "UTC"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Что бы запустить добавь тэг -B при запуске celery
CELERY_BEAT_SCHEDULE = {
    # "update-user-favorite-tracks-every-day": {
    #     "task": "SpotifyController.tasks.update_user_data.update_user_favorite_tracks",
    #     "schedule": crontab(hour="2", minute="0"),
    #     "args": (),
    # },
    # "save_users_listen_tracks-every-day": {
    #     "task": "SpotifyController.tasks.update_user_data.update_user_listen_tracks",
    #     "schedule": crontab(minute="*/5"),
    #     "args": (),
    # },
    # "update-artist-data-every-day":{
    #     "task": "SpotifyController.tasks.update_user_data.update_artist_data",
    #     "schedule": crontab(hour="3"),
    #     "args": (),
    # },
    # "update-user-recommendations-list-every-day": {
    #     "task": "SpotifyController.tasks.update_user_data.update_user_recommendations",
    #     "schedule": crontab(minute="*/10"),
    #     "args": (),
    # }
    # "update-user-playlists-every-day": {
    #     "task": "SpotifyController.tasks.update_user_data.update_user_playlists",
    #     "schedule": crontab(minute="*"),
    #     "args": (),
    # },
    "update_top_tracks-every-day": {
        "task": "Main.tasks.update_data.update_top_tracks",
        "schedule": crontab(minute="*/5"),
    },
    "update_top_artists-every-day": {
        "task": "Main.tasks.update_data.update_top_artists",
        "schedule": crontab(minute="*/5"),
    },
    # "clear_all_data-every-day": {
    #     "task": "Main.tasks.clear_data.clear_all_data",
    #     "schedule": crontab(hour="2"),
    # },
    # "update_recently_replayed_tracks-every-five-minutes": {
    #     "task": "Main.tasks.update_data.update_recently_replayed_tracks",
    #     "schedule": crontab(minute="*/5"),
    #     "args": (),
    # },
}

CELERY_TASK_ROUTES = {
    'SpotifyController.tasks.fetch_new_obj.*': {'queue': 'heavy_tasks'},
    'SpotifyController.tasks.update_user_data.update_user_playlists': {'queue': 'low_priority'},
}