# Generated by Django 5.2.8 on 2026-01-20 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpotifyController', '0020_album_album_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='TopAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.album')),
            ],
            options={
                'unique_together': {('album', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TopArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.artist')),
            ],
            options={
                'unique_together': {('artist', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TopTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.track')),
            ],
            options={
                'unique_together': {('track', 'position')},
            },
        ),
    ]
