# Generated by Django 5.2.8 on 2026-02-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('SpotifyController', '0021_postgres_extensions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopTracks',
            new_name='TopTrack',
        ),
        migrations.AlterUniqueTogether(
            name='topartists',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topartists',
            name='artist',
        ),
        migrations.CreateModel(
            name='TopAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.album')),
            ],
            options={
                'unique_together': {('album', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TopArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.artist')),
            ],
            options={
                'unique_together': {('artist', 'position')},
            },
        ),
        migrations.DeleteModel(
            name='TopAlbums',
        ),
        migrations.DeleteModel(
            name='TopArtists',
        ),
    ]
