# Generated by Django 5.2.8 on 2026-02-06 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_toptracks_toptrack_and_more'),
        ('SpotifyController', '0021_postgres_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topalbum',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topalbum',
            name='album',
        ),
        migrations.CreateModel(
            name='FreshPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayedTodayTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='Play Count')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.track', verbose_name='Track')),
                ('users', models.ManyToManyField(related_name='played_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyReplayedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replayed_count', models.PositiveIntegerField(default=0, verbose_name='Replayed Count')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotifyController.track', verbose_name='Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.DeleteModel(
            name='RecommendationPlaylist',
        ),
        migrations.DeleteModel(
            name='TopAlbum',
        ),
    ]
