# Generated by Django 5.2.8 on 2026-02-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_topalbum_unique_together_remove_topalbum_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshplaylist',
            name='user',
        ),
    ]
