# Generated by Django 5.2.8 on 2025-11-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('image', models.ImageField(null=True, upload_to='artists/', verbose_name='Image')),
                ('spotify_id', models.CharField(max_length=100, unique=True, verbose_name='Spotify id')),
                ('spotify_url', models.URLField(max_length=250, verbose_name='Artist Url')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteUserTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Track Name')),
                ('url', models.URLField(max_length=250, verbose_name='Track Url')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('spotify_id', models.CharField(max_length=100, unique=True, verbose_name='Spotify id')),
            ],
        ),
    ]
