# Generated by Django 5.2.8 on 2025-11-11 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpotifyController', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteusertracks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tracks_links', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='favoriteusertracks',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to='SpotifyController.track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='artist',
            name='track_list',
            field=models.ManyToManyField(blank=True, related_name='artists', to='SpotifyController.track', verbose_name='Track List'),
        ),
    ]
