# Generated by Django 5.2.8 on 2025-11-27 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpotifyController', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteusertracks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tracks_links', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(default=None, related_name='artists', to='SpotifyController.genre', verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='recommendationtracks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_links', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='recommendationtracks',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='SpotifyController.track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='favoriteusertracks',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='SpotifyController.track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='artist',
            name='track_list',
            field=models.ManyToManyField(blank=True, related_name='artists', to='SpotifyController.track', verbose_name='Track List'),
        ),
        migrations.AddField(
            model_name='userslistenhistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_history', to='SpotifyController.track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='userslistenhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_history_links', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
