# Generated by Django 5.2.8 on 2025-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Release Date'),
        ),
    ]
