# Generated by Django 5.2.8 on 2025-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteusertracks',
            name='term',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('medium_term', 'Medium Term'), ('long_term', 'Long Term')], default='short_term', max_length=15, verbose_name='Term'),
        ),
    ]
