# Generated by Django 5.2.8 on 2025-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0003_favoriteusertracks_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(null=True, upload_to='tracks/', verbose_name='Track Image'),
        ),
    ]
