# Generated by Django 5.2.8 on 2025-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0004_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview',
            field=models.URLField(max_length=250, null=True, verbose_name='Preview Url'),
        ),
    ]
