# Generated by Django 5.2.8 on 2025-11-16 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0004_genre_artist_genres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='SpotifyController.track', verbose_name='Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_links', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
