# Generated by Django 5.2.8 on 2025-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0005_track_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='preview',
        ),
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.URLField(max_length=250, null=True, verbose_name='Preview Url'),
        ),
    ]
