# Generated by Django 5.2.8 on 2025-12-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0006_remove_track_preview_track_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(null=True, verbose_name='Duration in ms'),
        ),
    ]
