# Generated by Django 5.2.8 on 2025-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0007_track_duration_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.FileField(max_length=250, null=True, upload_to='previews/', verbose_name='Preview Url'),
        ),
    ]
