# Generated by Django 5.2.8 on 2025-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0008_alter_track_preview_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='track',
            name='preview',
            field=models.FileField(max_length=250, null=True, upload_to='previews/', verbose_name='Preview Url'),
        ),
    ]
