# Generated by Django 5.2.8 on 2025-12-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0009_remove_track_preview_url_track_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='preview',
            field=models.FileField(max_length=250, null=True, upload_to='previews/', verbose_name='Preview Mp3'),
        ),
    ]
