# Generated by Django 5.2.8 on 2025-12-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0010_alter_track_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(default=0, verbose_name='Flowers'),
        ),
    ]
