# Generated by Django 5.2.8 on 2025-12-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0011_artist_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='top_tracks',
            field=models.ManyToManyField(blank=True, related_name='top_artist_tracks', to='SpotifyController.track', verbose_name='Top Tracks'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track_list',
            field=models.ManyToManyField(blank=True, related_name='artists_tracks', to='SpotifyController.track', verbose_name='Track List'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Album Name')),
                ('image', models.ImageField(null=True, upload_to='albums/', verbose_name='Album Image')),
                ('spotify_id', models.CharField(max_length=100, unique=True, verbose_name='Spotify id')),
                ('tracks', models.ManyToManyField(blank=True, related_name='albums', to='SpotifyController.track', verbose_name='Tracks')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='artists_albums', to='SpotifyController.album', verbose_name='Albums'),
        ),
    ]
