# Generated by Django 5.2.8 on 2025-12-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0012_artist_top_tracks_alter_artist_track_list_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='artists', to='SpotifyController.album', verbose_name='Albums'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track_list',
            field=models.ManyToManyField(blank=True, related_name='artists', to='SpotifyController.track', verbose_name='Track List'),
        ),
    ]
