# Generated by Django 5.2.8 on 2025-12-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0013_alter_artist_albums_alter_artist_track_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Release Date'),
        ),
        migrations.AddField(
            model_name='album',
            name='total_tracks',
            field=models.IntegerField(default=0, verbose_name='Total Tracks'),
        ),
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(max_length=200, null=True, verbose_name='Album Type'),
        ),
    ]
