# Generated by Django 5.2.8 on 2025-12-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0014_remove_track_release_date_album_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_url',
            field=models.URLField(max_length=250, null=True, verbose_name='Album Url'),
        ),
    ]
