# Generated by Django 5.2.8 on 2025-12-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0016_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='spotify_url',
            field=models.URLField(max_length=250, null=True, verbose_name='Spotify Url'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks_count',
            field=models.IntegerField(default=0, verbose_name='Tracks Count'),
        ),
    ]
