# Generated by Django 5.2.8 on 2025-12-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0017_playlist_description_playlist_spotify_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks_count',
        ),
        migrations.AddField(
            model_name='playlist',
            name='track_count',
            field=models.IntegerField(default=0, verbose_name='Tracks Count'),
        ),
    ]
