# Generated by Django 5.2.8 on 2026-01-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0018_remove_playlist_tracks_count_playlist_track_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='SpotifyController.track', verbose_name='Tracks'),
        ),
    ]
