# Generated by Django 5.2.8 on 2026-01-15 13:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0021_postgres_extensions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='album',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='album_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='artist_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='genre_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='track',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='track_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
