# Generated by Django 5.2.7 on 2025-11-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('spotify_id', models.CharField(max_length=255, null=True, verbose_name='Spotify ID')),
                ('access_token', models.CharField(max_length=255, null=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=255, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(null=True, verbose_name='Token Expires')),
                ('top_tracks_cache', models.JSONField(null=True, verbose_name='Top Tracks Cache')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
