# Generated by Django 5.2.8 on 2026-01-13 16:25

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyController', '0019_playlist_tracks'),
        ('User', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='customuser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='username_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
