# Generated by Django 5.2.7 on 2025-11-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=255, unique=True, verbose_name='Login')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m', verbose_name='User Image')),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotify ID')),
                ('followers', models.IntegerField(blank=True, default=0, verbose_name='Followers')),
                ('spotify_url', models.URLField(blank=True, null=True, verbose_name='Spotify Link')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires')),
                ('top_tracks_cache', models.JSONField(blank=True, null=True, verbose_name='Top Tracks Cache')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustromUser',
        ),
    ]
