# Generated by Django 5.2.7 on 2025-11-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='Andre', max_length=255, null=True, verbose_name='username'),
        ),
    ]
